INSERT INTO users (name, age) VALUES ("Nick", 25);
INSERT INTO users (name, age) VALUES ("Dylan", 24);
INSERT INTO users (name, age) VALUES ("Brian", 24);
INSERT INTO users (name, age) VALUES ("Chris", 23);
INSERT INTO users (name, age) VALUES ("Alex", 24);
INSERT INTO users (name, age) VALUES ("Conor", 24);
INSERT INTO users (name, age) VALUES ("Patrick", 25);
INSERT INTO users (name, age) VALUES ("Kevin", 24);
INSERT INTO users (name, age) VALUES ("Matt", 24);
INSERT INTO users (name, age) VALUES ("Eric", 24);
INSERT INTO users (name, age) VALUES ("Greg", 51);
INSERT INTO users (name, age) VALUES ("Beth", 51);
INSERT INTO users (name, age) VALUES ("Lauren", 22);
INSERT INTO users (name, age) VALUES ("Laura", 24);
INSERT INTO users (name, age) VALUES ("Maddie", 24);
INSERT INTO users (name, age) VALUES ("Danielle", 23);
INSERT INTO users (name, age) VALUES ("Penny", 24);
INSERT INTO users (name, age) VALUES ("Genevieve", 23);
INSERT INTO users (name, age) VALUES ("Anna", 24);
INSERT INTO users (name, age) VALUES ("Annie", 30);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cat", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dog", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mouse", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fox", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Eagle", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Giraffe", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Lion", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hamster", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rabbit", "Animals", 100, "January 1, 2010", "August 28, 2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gator", "Animals", 100, "January 1, 2010", "August 28, 2015");
